= Fabric8-NATS

Playing with NATS.io on OpenShift/Minishift

== Deploying NATS Streaming server

The NATS Streaming Server is not supported by the NATS-Operator https://github.com/nats-io/nats-operator/issues/18[yet], but it can be deployed using a regular `deployment` manifest:

```
$ oc apply -f openshift/nats-streaming-deployment.yaml
```

== Building and deploying the publisher

Each new version of the publisher is automatically deployed using an `ImageStream` and a `DeployConfig`:

```
# Create the ImageStream
oc apply -f openshift/publisher-imagestream.yaml

# create the DC
oc apply -f openshift/publisher-deployconfig.yaml
```

Then, building and deploying a new version of the publisher happens with

```
make deploy-publisher
```

== Building and deploying the subscribers

All subscribers share the same code but are configured differently in their DeployConfig.

To avoid repetition among the YAML files, both subscribers are created using the same OpenShift template:

```
# subscriber 1 with 0 replica 
$ oc process -f openshift/subscriber.tmpl.yaml -p SERVICE=subscriber1 -p REPLICA_COUNT=0 -p SUBJECTS=subject1 | oc apply -f -

# subscriber 2 with 0 replica
$ oc process -f openshift/subscriber.tmpl.yaml -p SERVICE=subscriber2 -p REPLICA_COUNT=0 -p SUBJECTS=subject2 | oc apply -f -
```

The template used above creates both the `ImageStream` and the `DeployConfig` resources for each subscriber. Once this is done, a new version of the code can be deployed with

```
$ make deploy-subscribers
```

== Checking the results


```
# start the nats-streaming-server (previous replicas was set to '0')
$ oc scale deploy/nats-streaming-server --replicas=1
deployment "nats-streaming-server" scaled

# check the logs in the server
$ oc logs -f nats-streaming-server-6f58fcd54f-6rfmt
[1] 2018/05/31 13:22:43.747038 [INF] STREAM: Starting nats-streaming-server[f8-nats-streaming-cluster] version 0.9.2
[1] 2018/05/31 13:22:43.747093 [INF] STREAM: ServerID: tQN0xcAYPEX43IDEoHErJB
[1] 2018/05/31 13:22:43.747095 [INF] STREAM: Go version: go1.9.5
[1] 2018/05/31 13:22:43.747693 [INF] Starting nats-server version 1.0.7
[1] 2018/05/31 13:22:43.747698 [INF] Git commit [not set]
[1] 2018/05/31 13:22:43.747761 [INF] Starting http monitor on 0.0.0.0:8222
[1] 2018/05/31 13:22:43.747876 [INF] Listening for client connections on 0.0.0.0:4222
[1] 2018/05/31 13:22:43.747879 [INF] Server is ready
[1] 2018/05/31 13:22:43.774350 [INF] STREAM: Recovering the state...
[1] 2018/05/31 13:22:43.774401 [INF] STREAM: No recovered state
[1] 2018/05/31 13:22:44.025119 [INF] STREAM: Message store is MEMORY
[1] 2018/05/31 13:22:44.025152 [INF] STREAM: ---------- Store Limits ----------
[1] 2018/05/31 13:22:44.025155 [INF] STREAM: Channels:                  100 *
[1] 2018/05/31 13:22:44.025158 [INF] STREAM: --------- Channels Limits --------
[1] 2018/05/31 13:22:44.025159 [INF] STREAM:   Subscriptions:          1000 *
[1] 2018/05/31 13:22:44.025161 [INF] STREAM:   Messages     :       1000000 *
[1] 2018/05/31 13:22:44.025162 [INF] STREAM:   Bytes        :     976.56 MB *
[1] 2018/05/31 13:22:44.025163 [INF] STREAM:   Age          :     unlimited *
[1] 2018/05/31 13:22:44.025164 [INF] STREAM:   Inactivity   :     unlimited *
[1] 2018/05/31 13:22:44.025166 [INF] STREAM: ----------------------------------
^C
 
# start the publisher (replica count was previously lowered to '0' to stop all publishing)
$ oc scale dc/publisher --replicas=1
deploymentconfig "publisher" scaled

# check the logs in the publisher
$ oc logs -f publisher-39-6qlx8
INFO[0000] opening connection to cluster 'f8-nats-streaming-cluster' on nats://nats-streaming-server:4222'...  id=publisher-39-6qlx8
INFO[0000] connection established with server at 'nats://nats-streaming-server:4222'  id=publisher-39-6qlx8
INFO[0003] published on subject 'subject1': 'message #1'  id=publisher-39-6qlx8
INFO[0003] published on subject 'subject2': 'message #1'  id=publisher-39-6qlx8
INFO[0006] published on subject 'subject1': 'message #2'  id=publisher-39-6qlx8
INFO[0006] published on subject 'subject2': 'message #2'  id=publisher-39-6qlx8
INFO[0009] published on subject 'subject1': 'message #3'  id=publisher-39-6qlx8
INFO[0009] published on subject 'subject2': 'message #3'  id=publisher-39-6qlx8
INFO[0012] published on subject 'subject1': 'message #4'  id=publisher-39-6qlx8
INFO[0012] published on subject 'subject2': 'message #4'  id=publisher-39-6qlx8
INFO[0015] published on subject 'subject1': 'message #5'  id=publisher-39-6qlx8
INFO[0015] published on subject 'subject2': 'message #5'  id=publisher-39-6qlx8
INFO[0018] published on subject 'subject1': 'message #6'  id=publisher-39-6qlx8
INFO[0018] published on subject 'subject2': 'message #6'  id=publisher-39-6qlx8
^C

# start 2 subscribers at once, configured with a durable subscription
# and an option to retrieve all available messages in the queue
$ oc scale dc/subscriber1 --replicas=2
deploymentconfig "subscriber1" scaled

# check the logs of the first subscriber 
# oc logs -f subscriber1-20-9gpfs
INFO[0000] opening connection to cluster 'f8-nats-streaming-cluster' on nats://nats-streaming-server:4222'...  id=subscriber1-20-9gpfs
INFO[0000] connection established with server at 'nats://nats-streaming-server:4222'  id=subscriber1-20-9gpfs
INFO[0000] listening on 'subject1'...                    id=subscriber1-20-9gpfs
INFO[0004] received message with subject 'subject1': 'message #14'  id=subscriber1-20-9gpfs
INFO[0010] received message with subject 'subject1': 'message #16'  id=subscriber1-20-9gpfs
INFO[0016] received message with subject 'subject1': 'message #18'  id=subscriber1-20-9gpfs
^C

# check the logs of the second subscriber
$ oc logs -f subscriber1-20-j4mgh
INFO[0000] opening connection to cluster 'f8-nats-streaming-cluster' on nats://nats-streaming-server:4222'...  id=subscriber1-20-j4mgh
INFO[0000] connection established with server at 'nats://nats-streaming-server:4222'  id=subscriber1-20-j4mgh
INFO[0000] listening on 'subject1'...                    id=subscriber1-20-j4mgh
INFO[0000] received message with subject 'subject1': 'message #1'  id=subscriber1-20-j4mgh
INFO[0000] received message with subject 'subject1': 'message #2'  id=subscriber1-20-j4mgh
INFO[0000] received message with subject 'subject1': 'message #3'  id=subscriber1-20-j4mgh
INFO[0000] received message with subject 'subject1': 'message #4'  id=subscriber1-20-j4mgh
INFO[0000] received message with subject 'subject1': 'message #5'  id=subscriber1-20-j4mgh
INFO[0000] received message with subject 'subject1': 'message #6'  id=subscriber1-20-j4mgh
INFO[0000] received message with subject 'subject1': 'message #7'  id=subscriber1-20-j4mgh
INFO[0000] received message with subject 'subject1': 'message #8'  id=subscriber1-20-j4mgh
INFO[0000] received message with subject 'subject1': 'message #9'  id=subscriber1-20-j4mgh
INFO[0000] received message with subject 'subject1': 'message #10'  id=subscriber1-20-j4mgh
INFO[0000] received message with subject 'subject1': 'message #11'  id=subscriber1-20-j4mgh
INFO[0000] received message with subject 'subject1': 'message #12'  id=subscriber1-20-j4mgh
INFO[0001] received message with subject 'subject1': 'message #13'  id=subscriber1-20-j4mgh
INFO[0007] received message with subject 'subject1': 'message #15'  id=subscriber1-20-j4mgh
INFO[0013] received message with subject 'subject1': 'message #17'  id=subscriber1-20-j4mgh
INFO[0019] received message with subject 'subject1': 'message #19'  id=subscriber1-20-j4mgh
INFO[0025] received message with subject 'subject1': 'message #21'  id=subscriber1-20-j4mgh
^C

```

=== Conclusion

With the `durable name` and `deliver all available` options in place, the 2 subscribers 
received all the messsage emited by the publisher, even when they were not running.