= Fabric8-NATS

Playing with NATS.io on OpenShift/Minishift

== Deploying NATS

These commands should deploy the https://github.com/nats-io/nats-operator[NATS.io operator]
in the OpenShift project specified by the `NAMESPACE` parameter in the template (this means
that the corresponding project must exist prior to applying the template)

```
# login as a system admin
$ oc login https://192.168.99.100:8443 --insecure-skip-tls-verify=true -u system:admin

# deploy the NATS operator in the `fabric8` project. This will deploy a pod and create a CRD, too.
$ oc process -f openshift/nats-operator.yaml -p NAMESPACE=fabric8 | oc apply -f -

# deploy a cluster with 3 replicas
$ oc apply -f nats-cluster.yaml
```

== Building and deploying the publisher

Each new version of the publisher is automatically deployed using an `ImageStream` and a `DeployConfig`:

```
# Create the ImageStream
oc apply -f openshift/publisher-imagestream.yaml

# create the DC
oc apply -f openshift/publisher-deployconfig.yaml
```

Then, building and deploying a new version of the publisher happens with

```
make deploy-publisher
```

== Building and deploying the subscribers

All subscribers share the same code but are configured differently in their DeployConfig.

To avoid repetition among the YAML files, both subscribers are created using the same OpenShift template:

```
# subscriber 1 with 0 replica 
$ oc process -f openshift/subscriber.tmpl.yaml -p SERVICE=subscriber1 -p REPLICA_COUNT=0 -p SUBJECTS=subject1 | oc apply -f -

# subscriber 2 with 0 replica
$ oc process -f openshift/subscriber.tmpl.yaml -p SERVICE=subscriber2 -p REPLICA_COUNT=0 -p SUBJECTS=subject2 | oc apply -f -
```

The template used above creates both the `ImageStream` and the `DeployConfig` resources for each subscriber. Once this is done, a new version of the code can be deployed with

```
$ make deploy-subscribers
```

== Checking the results


```
# check the pods
$ oc get pods
NAME                             READY     STATUS      RESTARTS   AGE
NAME                             READY     STATUS      RESTARTS   AGE
nats-operator-7956769cc9-n4sl2   1/1       Running     2          4d
nats-9zwhh5vmrn                  1/1       Running     0          31m
nats-t5pfn22bb9                  1/1       Running     0          31m
publisher-19-kc7ch               1/1       Running     0          3s


# checks the publisher logs 
oc logs -f publisher-19-kc7ch
time="2018-05-30T07:43:46Z" level=info msg="[publisher-19-kc7ch] opening connection to 'nats://example-nats-cluster:4222'..."
time="2018-05-30T07:43:46Z" level=info msg="[publisher-19-kc7ch] connection opened: 'true'..."
time="2018-05-30T07:43:49Z" level=info msg="[publisher-19-kc7ch] published on subject 'subject1': 'message #1'"
time="2018-05-30T07:43:49Z" level=info msg="[publisher-19-kc7ch] published on subject 'subject2': 'message #1'"
time="2018-05-30T07:43:52Z" level=info msg="[publisher-19-kc7ch] published on subject 'subject1': 'message #2'"
time="2018-05-30T07:43:52Z" level=info msg="[publisher-19-kc7ch] published on subject 'subject2': 'message #2'"
time="2018-05-30T07:43:55Z" level=info msg="[publisher-19-kc7ch] published on subject 'subject1': 'message #3'"
time="2018-05-30T07:43:55Z" level=info msg="[publisher-19-kc7ch] published on subject 'subject2': 'message #3'"
time="2018-05-30T07:43:58Z" level=info msg="[publisher-19-kc7ch] published on subject 'subject1': 'message #4'"
time="2018-05-30T07:43:58Z" level=info msg="[publisher-19-kc7ch] published on subject 'subject2': 'message #4'"
time="2018-05-30T07:44:01Z" level=info msg="[publisher-19-kc7ch] published on subject 'subject1': 'message #5'"
time="2018-05-30T07:44:01Z" level=info msg="[publisher-19-kc7ch] published on subject 'subject2': 'message #5'"
...

# now, schedule 1 instance for each subscriber
$ oc process -f openshift/subscriber.tmpl.yaml -p SERVICE=subscriber1 -p REPLICA_COUNT=1 -p SUBJECTS=subject1 | oc apply -f -
imagestream "subscriber1" unchanged
deploymentconfig "subscriber1" configured
$ oc process -f openshift/subscriber.tmpl.yaml -p SERVICE=subscriber2 -p REPLICA_COUNT=1 -p SUBJECTS=subject2 | oc apply -f -
imagestream "subscriber2" unchanged
deploymentconfig "subscriber2" configured
$ oc get pods
NAME                             READY     STATUS      RESTARTS   AGE
nats-operator-7956769cc9-n4sl2   1/1       Running     2          4d
nats-9zwhh5vmrn                  1/1       Running     0          34m
nats-t5pfn22bb9                  1/1       Running     0          34m
publisher-19-kc7ch               1/1       Running     0          3m
subscriber1-8-2qbn5              1/1       Running     0          43s
subscriber2-12-wrnpd             1/1       Running     0          36s


# check the logs on the single instance of subscriber 1
$ oc logs subscriber1-8-2qbn5
time="2018-05-30T07:46:12Z" level=info msg="[subscriber1-8-2qbn5] opening connection to 'nats://example-nats-cluster:4222'..."
time="2018-05-30T07:46:12Z" level=info msg="[subscriber1-8-2qbn5] connection opened: 'true'..."
time="2018-05-30T07:46:12Z" level=info msg="[subscriber1-8-2qbn5] listening on 'subject1'..."
time="2018-05-30T07:46:13Z" level=info msg="[subscriber1-8-2qbn5] received message with subject 'subject1' on queue 'queue-subject1': 'message #49'"
time="2018-05-30T07:46:16Z" level=info msg="[subscriber1-8-2qbn5] received message with subject 'subject1' on queue 'queue-subject1': 'message #50'"
time="2018-05-30T07:46:19Z" level=info msg="[subscriber1-8-2qbn5] received message with subject 'subject1' on queue 'queue-subject1': 'message #51'"
...

# check the logs on the first instance of subscriber 2
$ oc logs subscriber2-12-wrnpd
time="2018-05-30T07:46:19Z" level=info msg="[subscriber2-12-wrnpd] opening connection to 'nats://example-nats-cluster:4222'..."
time="2018-05-30T07:46:19Z" level=info msg="[subscriber2-12-wrnpd] connection opened: 'true'..."
time="2018-05-30T07:46:19Z" level=info msg="[subscriber2-12-wrnpd] listening on 'subject2'..."
time="2018-05-30T07:46:19Z" level=info msg="[subscriber2-12-wrnpd] received message with subject 'subject2' on queue 'queue-subject2': 'message #51'"
time="2018-05-30T07:46:22Z" level=info msg="[subscriber2-12-wrnpd] received message with subject 'subject2' on queue 'queue-subject2': 'message #52'"
time="2018-05-30T07:46:25Z" level=info msg="[subscriber2-12-wrnpd] received message with subject 'subject2' on queue 'queue-subject2': 'message #53'"
...
```

== Conclusion

While there were no instances of `subscriber1` and `subscriber2`, the messages that were not delivered were lost.